from models.resnet import ResNet18, ResNet34, ResNet50, ResNet101, WideResNet34_2, WideResNet50_2, WideResNet101_2
from models.resnet_BinAct import ResNet18_BinAct, ResNet34_BinAct, ResNet50_BinAct, ResNet101_BinAct, WideResNet18_2_BinAct, WideResNet18_3_BinAct, WideResNet34_2_BinAct, WideResNet34_3_BinAct, WideResNet50_2_BinAct, cifarResNet18_BinAct, cifarWideResNet18_2_BinAct, cifarWideResNet18_3_BinAct
from models.resnet_cifar import cResNet18, cWideResNet18_2, cResNet50, cResNet101, cResNet20, cResNet32, cResNet44, cResNet56, cResNet110
from models.resnet_cifar_v2 import cResNet18_v2
from models.resnet_cifar_BinAct import cResNet18_BinAct, cWideResNet18_2_BinAct, cWideResNet18_3_BinAct, cResNet34_BinAct, cResNet20_BinAct, cResNet32_BinAct, cResNet44_BinAct, cResNet56_BinAct, cResNet110_BinAct
from models.resnet_cifar_BinAct_v2 import cResNet18_BinAct_v2
from models.frankle import FC, Conv2, Conv2_BinAct, Conv4, Conv4_BinAct, Conv6, Conv6_BinAct, Conv4Wide, Conv4Wide_BinAct, Conv8, Conv8_BinAct, Conv6Wide, Conv6Wide_BinAct, Conv8Wide, Conv8Wide_BinAct, VGG_Small, VGG_Small_BinAct, VGG_Small_noReLU_BinAct, Conv8Wide_BinAct_ReLU, Conv8Wide_BinAct_ReLU_Final_Act, Wide_VGG_Small, Wide_VGG_Small_132, VGG_Small_bn_BinAct
from models.resnet_BinAct_v2 import ResNet34_BinAct_v2,WideResNet34_2_BinAct_v2,ResNet50_BinAct_v2,WideResNet50_2_BinAct_v2,WideResNet18_2_BinAct_v2, WideResNet34_3_BinAct_v2
from models.resnet_v2 import ResNet18_v2,ResNet34_v2,ResNet50_v2,WideResNet34_2_v2,WideResNet50_2_v2,WideResNet18_v2

__all__ = [
    "ResNet18",
    "ResNet18_BinAct",
    "ResNet34",
    "ResNet34_BinAct",
    "ResNet50",
    "ResNet50_BinAct",
    "ResNet101",
    "ResNet101_BinAct",
    "cResNet18",
    "cResNet20",
    "cResNet32",
    "cResNet44",
    "cResNet56",
    "cResNet110",
    "cResNet20_BinAct",
    "cResNet32_BinAct",
    "cResNet44_BinAct",
    "cResNet56_BinAct",
    "cResNet110_BinAct",
    "cResNet18_BinAct",
    "cifarResNet18_BinAct",
    "cWideResNet18_2", 
    "WideResNet18_2_BinAct", 
    "WideResNet18_3_BinAct", 
    "cWideResNet18_2_BinAct", 
    "cWideResNet18_3_BinAct", 
    "cResNet34_BinAct",
    "cifarWideResNet18_2_BinAct", 
    "cifarWideResNet18_3_BinAct", 
    "cResNet50",
    "WideResNet34_2",
    "WideResNet34_2_BinAct",
    "WideResNet34_3_BinAct",
    "WideResNet50_2",
    "WideResNet50_2_BinAct",
    "WideResNet101_2",
    "FC",
    "Conv2",
    "Conv2_BinAct",
    "Conv4",
    "Conv4_BinAct",
    "Conv6",
    "Conv6_BinAct",
    "Conv4Wide",
    "Conv4Wide_BinAct",
    "Conv8",
    "Conv8_BinAct",
    "Conv6Wide",
    "Conv6Wide_BinAct",
    "Conv8Wide",
    "Conv8Wide_BinAct",
    "Conv8Wide_BinAct_ReLU", 
    "Conv8Wide_BinAct_ReLU_Final_Act", 
    "VGG_Small",
    "VGG_Small_BinAct",
    "VGG_Small_noReLU_BinAct",
    "Wide_VGG_Small",
    "Wide_VGG_Small_132",
    "VGG_Small_bn_BinAct",
    "ResNet34_BinAct_v2",
    "WideResNet34_2_BinAct_v2",
    "ResNet50_2_BinAct_v2",
    "WideResNet50_2_BinAct_v2",
    "WideResNet50_2_v2",
    "WideResNet34_2_v2",
    "ResNet50_v2",
    "ResNet34_v2",
    "ResNet18_v2",
    "WideResNet18_2_BinAct_v2",
    "WideResNet18_v2",
    "WideResNet34_3_BinAct_v2",
    "cResNet18_BinAct_v2",
    "cResNet18_v2",
]
